### PR TITLE
JS-7 Mosaic Restrictions enhancements

### PR DESCRIPTION
**Pull request by fullcircle23**
Changes:

- Added MosaicGlobalRestrictionTransaction
- Added missing copyright comments
- Move MosaicAddressRestrictionTransaction and MosaicAddressRestrictionTransactionFactory from _test_ to _main_
- Some refactorings

### CODE REVIEW

**Comment by fullcircle23** [comment]
This PR is for #76

**Comment by fullcircle23** [comment]
> restrictionKey
Hi @rg911, Will catbuffer continue to use `long` for restrictionKey and restrictionValue?

**Comment by rg911** [comment]
Catbuffer still uses uint64, perhaps we keep bigint for now, as we have the convert methods to do the conversion. If there is a cr we can always change it later

**Comment by fullcircle23** [comment]
> Catbuffer still uses uint64, perhaps we keep bigint for now, as we have the convert methods to do the conversion. If there is a cr we can always change it later

Done the changes but will stash them as discussed to keep consistency with TS, we'll maintain those fields as BigInt.

**Comment by fullcircle23** [comment]
> 1. Some of the mapper classes are still missing javadoc ??
> 2. Need to add e2e / integration test for these restriction txs??

1. Thanks for catching that.. some of the mapper classes in openapi clients indeed are missing javadocs. i'll add them in.
2. Yes. Will add these.

**Pull request merged**
